### ISSUE TITLE
Superscript q doesn't render on Apple devices

### ISSUE THREAD

**Issue by molund** [bcgov/bc-sans#10]
The indigenous name for Brooks Penninsula Park contains a superscript q which renders properly on Windows but doesn't render on Mac or iOS devices.  I think maybe it's not supported in Windows either but it's falling back to a different system font.

𐞥 
U+107A5 : MODIFIER LETTER SMALL Q

**Comment by ShawnTurple** [comment]
@molund can you confirm this is the issue, the difference between the image  overlay, and the text
![image](https://github.com/bcgov/bc-sans/assets/45861534/e3db17d0-5ebc-4dea-a152-ab6165abc017)

**Comment by molund** [comment]
There is a high likelihood that the superscript q was used **in error** in the Protected Areas of British Columbia Amendment Act of 2018, but now it is part of BC Law, and it may require new legislation to change it.  

https://www.bclaws.gov.bc.ca/civix/document/id/hstats/hstats/2089126546
https://www.canlii.org/en/bc/laws/stat/sbc-2000-c-17/latest/sbc-2000-c-17.html

It's probably supposed to be the "Canadian Syllabics Ke" character, not a superscript q.
https://www.compart.com/en/unicode/U+146B

Having support for the superscript q might still be very helpful in the meantime.

**Comment by marcoT0425** [comment]
The problem is still not fixed. I'm using MacBook Air Sequoia. The issue is still not fixed. :(

<img width="342" height="67" alt="Image" src="https://github.com/user-attachments/assets/4cd07108-75a1-43ee-ae4e-5c648ac26e37" />

Please create this character: 𐞥 (Unicode 14.0)
M𐞥uqᵂin Park (instead of Mᑫuqᵂin Park)
