### ISSUE TITLE
Maven package

### ISSUE THREAD

**Issue by smithkm** [bcgov/bc-sans#6]
It would be helpful to have the OTFs and TTFs available as Maven packages to ease integration into apps that need to do their own text rendering like GeoServer installations or apps that generate PDFs.  A package for the web fonts via Maven probably wouldn't hurt either.

**Comment by ShawnTurple** [comment]
@smithkm our team has taken over this repo for now, and just wondering if this was still an issue, and if so, maybe you can reach out to me, with more details.

**Comment by ShawnTurple** [comment]
closing this issue, as no update from @smithkm
